create table if not exists memories (
  id bigint generated by default as identity primary key,

  memory text not null,

  emotion text not null,

  feeling text not null,

  reflection text not null,

  category text not null,

  created_at timestamptz
    default now()
);


alter table memories
enable row level security;


drop policy if exists
"Anyone can read memories"
on memories;


drop policy if exists
"Anyone can create memories"
on memories;


create policy
"Anyone can read memories"
on memories
for select
to anon
using (true);


create policy
"Anyone can create memories"
on memories
for insert
to anon
with check (true);
